cell_type: SHSY5Y, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_100.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_10.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_1.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.100_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.010_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_10.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_1.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_100.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_10.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_1.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.100_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.010_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_10.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_1.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_100.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_10.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_1.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.100_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.010_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_10.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_1.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_100.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_10.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_1.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.100_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.010_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_10.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: SHSY5Y, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_1.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_100.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_10.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_1.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.100_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.010_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_10.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_1.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_100.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_10.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_1.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.100_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.010_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_10.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: True, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_1.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_100.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_10.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_1.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.100_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.010_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_10.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: True, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_1.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_100.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_10.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_1.000_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.100_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: LPS_0.010_ug_per_ml_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_10.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
cell_type: PBMC, aggregation: False, nomic: False, flag: True, control: DMSO_0.100_%_DMSO_0.025_%, treatment: Thapsigargin_1.000_uM_DMSO_0.025_%
Input Notebook:  split_data.ipynb
Output Notebook: split_data.ipynb
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/Interstellar/lib/python3.10/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'split_data.ipynb'
[NbConvertApp] WARNING | Config option `kernel_spec_manager_class` not recognized by `NbConvertApp`.
[NbConvertApp] Converting notebook 0.split_data_binary_classification.ipynb to script
[NbConvertApp] Writing 6874 bytes to scripts/0.split_data_binary_classification.py
